apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-crash
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: sdcrepo.azurecr.io/worker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: FAIL
              value: "2"
